name: omega_gps
description: Application GPS + Intercom (OMEGA).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Carto / géoloc
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  google_directions_api: ^0.10.0
  google_polyline_algorithm: ^3.1.0
  geocoding: ^3.0.0
  # APIs pour GPS premium
  weather: ^3.1.1
  flutter_tts: ^3.8.3
  
  # Intercom LiveKit
  livekit_client: ^2.5.0+hotfix.3
  volume_controller: ^2.0.7

  # Services en arrière-plan
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.2.5
  flutter_local_notifications: ^18.0.1

  # Utilitaires
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  http: ^1.1.0
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/map_styles/
