name: omega_intercom
description: Une application GPS moderne pour motards.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Plugins essentiels pour le GPS ---
  # Le plugin officiel pour intégrer Google Maps
  google_maps_flutter: ^2.5.0
  # Le plugin pour accéder au capteur GPS du téléphone
  geolocator: ^12.0.0
  # Un plugin pour effectuer des appels à des APIs (comme l'API Google Directions)
  http: ^1.2.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/map_styles/