name: omega_intercom
description: Application Intercom + GPS (OMEGA) avec SFU mediasoup et WebRTC.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Temps réel / audio / SFU
  mediasfu_mediasoup_client: ^0.0.8   # fork mediasoup client compatible Dart 3
  flutter_webrtc: ^1.0.0              # plugin officiel Flutter WebRTC
  socket_io_client: ^2.0.3+1          # stable (compatible Socket.IO v4)

  # Carto / géoloc
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2

  # HTTP & utilitaires
  http: ^1.2.2
  audio_session: ^0.2.2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/map_styles/
