name: omega_intercom
description: Une application GPS moderne pour motards.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  http: ^1.2.1
  flutter_google_places_sdk: ^0.4.2+1

  # --- Plugins Intercom mis à jour ---
  permission_handler: ^11.3.1 # Pour gérer toutes les permissions
  record: ^6.1.1             # Pour enregistrer l'audio
  flutter_sound: ^9.3.0

  cupertino_icons: ^1.0.6
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # On déclare uniquement les assets pour les styles de carte
  assets:
    - assets/map_styles/
